development:
  adapter: postgresql
  database: my_database_development
  host: localhost

test:
  adapter: postgresql
  database: my_database_test
  host: localhost


production:
  adapter: postgresql
  database: my_database_production
